# Generated by Django 6.0.3 on 2026-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_department_description_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='seniority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True),
        ),
    ]
