# Generated by Django 6.0.3 on 2026-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_exam_holiday_timetable_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
