# Generated by Django 6.0.3 on 2026-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gQP5h82zWP4pNDXIVuIRjexv3CpuFM3k', editable=False, max_length=32, unique=True),
        ),
    ]
